general.import = ["~/.config/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.95

[font]
normal = { family = "JetBrainsMono NFP", style = "Regular" }
bold = { family = "JetBrainsMono NFP", style = "Bold" }
italic = { family = "JetBrainsMono NFP", style = "Italic" }
size = 11

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Slash", mods = "Control", chars = "\u001f" }, # fixes ctrl+/ on windows
  { key = "Space", mods = "Control", chars = "\u0000" }, # fixes ctrl+space on windows
]
