general.import = ["~/.config/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.9

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
size = 12

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
]
