add_newline = true
command_timeout = 1000

format = "[$os$username$directory$git_branch$git_status]($style)\n$shell$character"

[os]
disabled = false
format = "[$symbol]($style) "
style = "blue"

[username]
disabled = false
show_always = true
format = "[$user]($style) "
style_root = "bold red"
style_user = "bold cyan"

[directory]
disabled = false
truncation_length = 2
truncation_symbol = "…/"
read_only = "󱀰"
style = "bold green"
format = "[$read_only]($read_only_style)[$path]($style)"
before_repo_root_style = "bold green"
repo_root_style = "bold green"
repo_root_format = "[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) "

[git_branch]
disabled = false
symbol = ""
format = "[$symbol $branch]($style) "
style = "italic purple"

[git_status]
disabled = false
format = '[$all_status]($style) '
style = "cyan"
ahead = "[⇡${count}](red) "
diverged = "[⇕⇡${ahead_count} ⇣${behind_count}](red) "
behind = "[⇣${count}](red) "
conflicted = "[](red) "
up_to_date = "[](green) "
untracked = "[?](blue) "
modified = "[](yellow) "
stashed = ""
staged = ""
renamed = ""
deleted = ""

[shell]
disabled = false
format = "[$indicator]($style) "
style = 'bright-black'
pwsh_indicator = "pwsh"
unknown_indicator = "?"

[character]
disabled = false
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"
vimcmd_symbol = "[](green)"
vimcmd_visual_symbol = "[](yellow)"
vimcmd_replace_symbol = "[](red)"
vimcmd_replace_one_symbol = "[](red)"

[aws]
symbol = ""

[buf]
symbol = ""

[bun]
symbol = ""

[c]
symbol = ""

[cpp]
symbol = ""

[cmake]
symbol = ""

[conda]
symbol = ""

[crystal]
symbol = ""

[dart]
symbol = ""

[deno]
symbol = ""

[docker_context]
symbol = ""

[elixir]
symbol = ""

[elm]
symbol = ""

[fennel]
symbol = ""

[fortran]
symbol = ""

[fossil_branch]
symbol = ""

[gcloud]
symbol = ""

[git_commit]
tag_symbol = ''

[golang]
symbol = ""

[gradle]
symbol = ""

[guix_shell]
symbol = ""

[haskell]
symbol = ""

[haxe]
symbol = ""

[hg_branch]
symbol = ""

[hostname]
ssh_symbol = ""

[java]
symbol = ""

[julia]
symbol = ""

[kotlin]
symbol = ""

[lua]
symbol = ""

[memory_usage]
symbol = "󰍛"

[meson]
symbol = "󰔷"

[nim]
symbol = "󰆥"

[nix_shell]
symbol = ""

[nodejs]
symbol = ""

[ocaml]
symbol = ""

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[package]
symbol = "󰏗"

[perl]
symbol = ""

[php]
symbol = ""

[pijul_channel]
symbol = ""

[pixi]
symbol = "󰏗"

[python]
symbol = ""

[rlang]
symbol = "󰟔"

[ruby]
symbol = ""

[rust]
symbol = "󱘗"

[scala]
symbol = ""

[status]
symbol = ""

[swift]
symbol = ""

[xmake]
symbol = ""

[zig]
symbol = ""
